# Generated by Django 4.2.5 on 2023-12-28 03:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("monitor", "0002_nginxrtmptoken"),
    ]

    operations = [
        migrations.CreateModel(
            name="Baby",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid1,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("birth_date", models.DateField()),
                (
                    "gender",
                    models.CharField(choices=[("男", "男"), ("女", "女")], max_length=1),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BabyMonitorData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event",
                    models.CharField(
                        choices=[("看不到脸", "看不到脸"), ("哭", "哭"), ("翻身", "翻身")],
                        max_length=128,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "baby",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="monitor.baby"
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
